FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ /app/src/

# Environment configurations
ENV PORT=5000
ENV FLASK_APP=src.web:app

# Expose port
EXPOSE 5000

# Run the application with gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "src.web:app"]
